CREATE TABLE Kunde (
    id INTEGER AUTO_INCREMENT NOT NULL,
    film VARCHAR(255) NOT NULL,
    fornavn VARCHAR(255) NOT NULL,
    etternavn VARCHAR(255) NOT NULL,
    tlfnr VARCHAR(20) NOT NULL,
    epost VARCHAR(255) NOT NULL,
    antall INTEGER NOT NULL,
        PRIMARY KEY(id)
);